### ISSUE TITLE
regression in testflows.trunk.cDK.cdkTestConnectivity

### ISSUE THREAD

**Issue by egonw** [cdk/nodes4knime#4]
```
junit.framework.AssertionFailedError: Node 'Table Difference Checker 0:41' is not executed. Error message is: Execute failed: Wrong value in row 'Row0' and column 'Molecule': expected '[Na+]', got '[C@H]1(C(N2[C@@]1(SC([C@@H]2C([O-])=O)(C)C)[H])=O)NC(=O)[C@@H](c3ccc(cc3)O)N.[Na+]' in line 1 (using checker 'Strings')
	at org.knime.testing.core.ng.WorkflowExecuteTest.checkExecutionStatus(WorkflowExecuteTest.java:218)
	at org.knime.testing.core.ng.WorkflowExecuteTest.run(WorkflowExecuteTest.java:170)
	at org.knime.testing.core.ng.WorkflowTestSuite.run(WorkflowTestSuite.java:238)
	at org.knime.testing.core.ng.WorkflowTestSuite.runTest(WorkflowTestSuite.java:305)
	at org.knime.testing.core.ng.TestflowRunnerApplication.runAllTests(TestflowRunnerApplication.java:254)
	at org.knime.testing.core.ng.TestflowRunnerApplication.access$1(TestflowRunnerApplication.java:227)
	at org.knime.testing.core.ng.TestflowRunnerApplication$1.call(TestflowRunnerApplication.java:172)
	at org.knime.testing.core.ng.TestflowRunnerApplication$1.call(TestflowRunnerApplication.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by egonw** [comment]
@sithmein, I cannot find the testflows.trunk.cDK.cdkTestConnectivity class... not in this repository, but not in SVN either... where should I look for the code of this test?

**Comment by egonw** [comment]
Quick update... I'm visiting the Dutch eScience Center soon, to gain more practical experience with running the community test suites and perhaps also about making releases.

**Comment by egonw** [comment]
This is fixed now. I figured out today where to get the test pathways, identified the cause of the fail (missing sorting in the test), fixed it, and we have green light on the Jenkins integration server since around noon.

![image](https://user-images.githubusercontent.com/26721/37254852-fda5894e-2543-11e8-9e3e-476201023b83.png)
